version: '2'
services:
  base:
    tty: true
    stdin_open: true
    build:
      context: .
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_NAME=book_purchase_development
      - DATABASE_USR=postgres
      - DATABASE_PWD=root
      - RAILS_ENV=development

  web:
    extends: base
    command: bash -c "bundle exec rake db:migrate && bundle exec puma -p 80"
    volumes:
      - ./:/app
    ports:
      - "3000:80"
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=book_purchase_development
    volumes:
      - postgresdata:/var/lib/postgresql/data

volumes:
  postgresdata:
