version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/DockerFile
    environment:
      - SECRET_KEY_BASE=$SECRET_KEY_BASE
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_NAME=$DATABASE_NAME
      - DATABASE_USR=$DATABASE_USR
      - DATABASE_PWD=$DATABASE_PWD
      - RAILS_ENV=$RAILS_ENV
      - NGAN_LUONG_CHECKOUT_URL=$NGAN_LUONG_CHECKOUT_URL
      - NGAN_LUONG_MERCHANT_ID=$NGAN_LUONG_MERCHANT_ID
      - NGAN_LUONG_MERCHANT_PASS=$NGAN_LUONG_MERCHANT_PASS
      - NGAN_LUONG_NOTIFICATION_EMAIL=$NGAN_LUONG_NOTIFICATION_EMAIL
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - postgresdata:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: ./docker/web/DockerFile
    depends_on:
      - app
    ports:
      - 80:80

volumes:
  postgresdata:
