version: '2'
services:
  base:
    tty: true
    stdin_open: true
    build:
      context: .
    environment:
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_NAME=$DATABASE_NAME
      - DATABASE_USR=$DATABASE_USR
      - DATABASE_PWD=$DATABASE_PWD
      - RAILS_ENV=$RAILS_ENV

  web:
    extends: base
    command: bash -c "bundle exec rake db:migrate && bundle exec puma -p 80"
    environment:
      - SECRET_KEY_BASE=$SECRET_KEY_BASE
    volumes:
      - ./:/app
    ports:
      - "3000:80"
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - postgresdata:/var/lib/postgresql/data

volumes:
  postgresdata:
