version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.17

    steps:
      - checkout

      - deploy:
          name: Deploy to remote server
          command: |
            ssh -o StrictHostKeyChecking=no user@your-remote-server "cd app && git pull origin master"

      - deploy:
          name: Run script on remote server
          command: |
            ssh -o StrictHostKeyChecking=no user@your-remote-server "cd app && bundle exec rake db:migrate && bundle exec puma -p 80"
