version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.17

    steps:
      - checkout

      - deploy:
          name: Pull latest source code
          command: |
            ssh -o StrictHostKeyChecking=no root@161.35.193.239 "cd app/book && git pull origin master"

      - deploy:
          name: Start application
          command: |
            ssh -o StrictHostKeyChecking=no root@161.35.193.239 "cd app/book && docker-compose -f docker-compose.production.yml down && docker-compose up --build "
