module ApplicationHelper
  def banks
    [
      "",
      "VCB - NH TMCP Ngoai Thuong Viet Nam",
      "BIDV - NH TMCP Dau tu va Phat trien Viet Nam",
      "VIETBANK - NH TMCP Viet Nam Thuong Tin",
      "TCB - NH TMCP Ky thuong Viet Nam",
      "STB - NH TMCP Sai Gon Thuong Tin",
      "VPB - NH TMCP Viet Nam Thinh Vuong",
      "EIB - NH TMCP Xuat nhap khau Viet Nam",
      "ABB - NH TMCP An Binh",
      "AGRIBANK - NH NN Va PTNT Viet Nam",
      "BAB - NH TMCP Bac A",
      "BVB - NH TMCP Bao Viet",
      "CBB - NH TM TNHH MTV Xay Dung Viet Nam",
      "CIMB - NH TNHH MTV CIMB",
      "COOPBANK - NH Hop tac xa Viet Nam",
      "DBS - NH DBS chi nhanh HCM",
      "DOB - NH TMCP Dong A",
      "GPB - NH TM TNHH MTV Dau Khi Toan Cau",
      "HDB - NH TMCP Phat Trien Thanh Pho Ho Chi Minh",
      "HLB - NH TNHH MTV Hongleong Viet Nam",
      "HSBC - Ngan hang TNHH MTV HSBC (Viet Nam)",
      "IBK - NH IBK - chi nhanh HCM",
      "IBK - NH IBK - chi nhanh Ha Noi",
      "ICB - NH TMCP Cong Thuong Viet Nam",
      "IVB - NH TNHH Indovina",
      "KBHCM - Kookmin Chi nhanh Thanh pho Ho Chi Minh",
      "KBHN - Kookmin Chi nhanh Ha Noi",
      "KEB Hana - Chi nhanh Ha Noi",
      "KEB Hana - Chi nhanh Thanh pho Ho Chi Minh",
      "KLB - NH TMCP Kien Long",
      "KSK - Dai chung TNHH Kasikornbank - Chi nhanh TP. HCM",
      "LPB - NH TMCP Buu Dien Lien Viet",
      "MAFC - CTY Tai chinh TNHH MTV Mirae Asset (Viet Nam)",
      "MB - NH TMCP Quan Doi",
      "MSB - NH TMCP Hang Hai Viet Nam",
      "NAB - NH TMCP Nam A",
      "NCB - NH TMCP Quoc Dan",
      "NH TMCP Phuong Dong (Liobank)",
      "NONGHYUP - Chi nhanh HN",
      "OCB - NH TMCP Phuong Dong",
      "Oceanbank - NH TMCP Dai Duong",
      "PBVN - NH TNHH MTV Public Viet Nam",
      "PGB - NH TMCP Xang Dau Petrolimex",
      "PVCB - NH TMCP Dai Chung Viet Nam",
      "SCB - NH TMCP Sai Gon",
      "SEAB - NH TMCP Dong Nam A",
      "SGB - NH TMCP Sai Gon Cong Thuong",
      "SHB - NH TMCP Sai Gon - Ha Noi",
      "SHBVN - NH TNHH MTV Shinhan Viet Nam",
      "TMCP Viet Nam Thinh Vuong - Ngan hang so CAKE by VPBank",
      "TMCP Viet Nam Thinh Vuong - Ngan hang so Ubank by VPBank",
      "TNHH MTV Standard Chartered Bank (Vietnam) Limited",
      "TPB - NH TMCP Tien Phong",
      "Timo by Ban Viet Bank - Ngân hàng số Timo",
      "UMEE - Ngan hang so UMEE by Kienlongbank",
      "UOB - NH TNHH MTV United Overseas Bank",
      "VAB - NH TMCP Viet A",
      "VBSP - Ngan hang Chinh sach Xa hoi",
      "VCCB - NH TMCP Ban Viet",
      "VIB - NH TMCP Quoc te Viet Nam",
      "VNPT Money - TT DV TC so VNPT - CN Tong cong ty truyen thong",
      "VRB - NH Lien Doanh Viet Nga",
      "Viettel Money - TCT DV so Viettel - CN Tap doan CN VT Quan doi",
      "WOO - NH Wooribank"
    ]
  end
end
